### PR TITLE
fixed several Github issues

### PR DESCRIPTION
**Pull request by wle8300**
- https://github.com/ckcollab/ckcollab/issues/138
- https://github.com/ckcollab/ckcollab/issues/137
- https://github.com/ckcollab/ckcollab/issues/116
- https://github.com/ckcollab/ckcollab/issues/139
- https://github.com/ckcollab/ckcollab/issues/92
- https://github.com/ckcollab/ckcollab/issues/98

### CODE REVIEW

**Review by sw00d — COMMENTED** [review]
Screen Shot 2021-09-01 at 11 43 42 AM

This is the mobile view of the about use page. I think this is uninteded?

**Comment by sw00d** [comment]
Should we update this button's styles (at the bottom of a blog)

Screen Shot 2021-09-01 at 11 44 49 AM

**Comment by sw00d** [comment]
Also I'm not seeing how #98 was resolved. Are there buttons I missing?

**Comment by wle8300** [comment]
> Screen Shot 2021-09-01 at 11 43 42 AM
> 
> This is the mobile view of the about use page. I think this is uninteded?

That's weird.... this is what it looks like for me. Which browser produces that bug?

https://user-images.githubusercontent.com/150245/131734454-43768bd0-b8dd-4f21-8ee2-de5af9ee76e0.mov

**Review by sw00d — APPROVED** [review]
Looks solid

**Pull request merged**
